#!/bin/bash
source /home/fabian/hdd/d/programs/bash_scripts/sane
# This script helps filling my Corona sheet: docs.google.com/spreadsheets/d/1uDTghO_ZYBs5nfs2kDc0Ms6e9bbx7clx_QgkWii7OMY
# It parses various online sources (much later edit: only two still working) and then either copies the entire data column into the clipboard or displays the latest value.
# Feedback: fabianroeling@googlemail.com

# open sheet
(firefox "docs.google.com/spreadsheets/d/1uDTghO_ZYBs5nfs2kDc0Ms6e9bbx7clx_QgkWii7OMY" &> /dev/null & disown)
# vaccination world: get matching rows, start at 2021-04-17, extract 6th column
echo -n "total\n$(wget -qO - "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv" | grep "World" | tail -n +162 | sed "s/([^\,]*\,){6}([^\,]*)\,.*/\2/")" | xclip -selection clipboard; echo -n "paste: vaccination_world"; read
# download page, find series name on website, get number list ("data"), remove prefix, remove suffix, "null"→"0", negatives→0, split on commas, align to 2021-04-17
echo -n "reported\n$(wget -qO - "worldometers.info/coronavirus" | grep -im 1 --after-context=5 "name: 'Currently infected'" | grep "data" | sed "s/ *data\\: \\[//;s/\\] *\\} *\\]? *\\,? *\\{? *//;s/null/0/g;s/\\-[0-9]+/0/g;s/\\,/\\n/g" | tail -n +447)" | xclip -selection clipboard; echo -n "paste: cases_world"
xdotool key q sleep 0.1 key return