#!/bin/bash
# allow direct usage of bash scripts like commands
export PATH="/home/fabian/hdd/d/programs/bash_scripts:$PATH"
# aliases in functions (and here) work
shopt -s expand_aliases
# all regexes work in sed
alias sed="sed -E"
# finish line after cat commands, so that command prompt doesn't appear to the right of the last line
cat(){ echo "$(/usr/bin/cat "$@")";}
# escape sequences work in echo
alias echo="echo -e"
# don't warn for technically not necessary backslashes
grep(){ /usr/bin/grep "$@" 2>/dev/null;}
# increase console history size from 500 to unlimited
HISTSIZE=
HISTFILESIZE=