name: temp
on: [push,pull_request,workflow_dispatch]
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "hahaha" >> temp
          git add .
          git commit -m "temp"
          git push
