name: temp
on: [push,pull_request,workflow_dispatch]
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "hahaha" > tempa
          git config --global user.name "Fabian42"
          git config --global user.email "Fabian42@users.noreply.github.com"
          git add .
          git commit -m "temp"
          git push
