name: temp
on: [push,pull_request,workflow_dispatch]
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: temp
        uses: actions/checkout@v3
        run: |
          echo "testing" >> temp
